version: "3.9"
services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.0.1
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - dev-network
#
#  broker:
#    image: confluentinc/cp-kafka:7.0.1
#    container_name: broker
#    ports:
#      # To learn about configuring Kafka for access across networks see
#      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    networks:
#      - dev-network
  #    environment:
  #      KAFKA_BROKER_ID: 1
  #      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
  #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api-gateway-app:
    image: mikhailmi/api-gateway-app:master
    container_name: api-gateway-app
    hostname: api-gateway-app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    networks:
      - dev-network
    depends_on:
      - product-app
      - order-app
      - customer-app

  product-app:
    image: mikhailmi/product-app:master
    container_name: product-app
    hostname: product-app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: product/Dockerfile
    networks:
      - dev-network
    depends_on:
      - product-postgres

  customer-app:
    image: mikhailmi/customer-app:master
    container_name: customer-app
    hostname: customer-app
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: customer/Dockerfile
    networks:
      - dev-network
    depends_on:
      - product-postgres

  order-app:
    image: mikhailmi/order-app:master
    container_name: order-app
    hostname: order-app
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: order/Dockerfile
    networks:
      - dev-network
    depends_on:
      - product-postgres

  product-postgres:
    image: postgres:13
    hostname: product-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - product-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      POSTGRES_DB: product
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U product -d product" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  product-postgres-data:
  customer-postgres-data:

networks:
  dev-network:
    driver: bridge